server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: account-route
          uri: ${POSTS_ROUTE_URI:http://localhost:8081}
          predicates:
            - Path=/account
          filters:
            - PrefixPath=/api
