version: '3.7'

services:
  init-kafka:
    image: confluentinc/cp-kafka:latest
    entrypoint: ['/bin/sh', '-c']
    # For mac
    platform: linux/amd64
    command: |
      "
      echo -e 'Deleting kafka topics...'

      kafka-topics --delete --topic debezium.account.appointment_outbox --bootstrap-server localhost:29092 --if-exists
      kafka-topics --delete --topic debezium.appointment.availability_outbox --bootstrap-server localhost:29092 --if-exists
      kafka-topics --delete --topic debezium.pet.appointment_outbox --bootstrap-server localhost:29092 --if-exists

      kafka-topics --create --topic debezium.account.appointment_outbox --bootstrap-server localhost:29092 --if-not-exists
      kafka-topics --create --topic debezium.appointment.availability_outbox --bootstrap-server localhost:29092 --if-not-exists
      kafka-topics --create --topic debezium.pet.appointment_outbox --bootstrap-server localhost:29092 --if-not-exists

      echo -e 'Created kafka topics of'
      kafka-topics --bootstrap-server localhost:29092 --list
      "
    network_mode: host