
server:
  port: 8181

logging:
  level:
    com.vet.appointment.system: DEBUG
    org:
      springframework: INFO

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: "account-service"
  jpa:
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?stringtype=unspecified
    username: user
    password: admin
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      schema-locations: classpath:init-schema.sql
      mode: always
      platform: postgres