
# Application config
account-service:
  outbox-scheduler-delay: 10000
  outbox-scheduler-rate: 10000

server:
  port: 8181

# Logging
logging:
  level:
    com.vet.appointment.system: DEBUG
    org:
      springframework: DEBUG

# Service registry
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

# Database
spring:
  application:
    name: "account-service"
  jpa:
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?stringtype=unspecified
    username: user
    password: admin
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      schema-locations: classpath:init-schema.sql
      mode: always
      platform: postgres

# Kafka
kafka-config-data:
  bootstrap-servers: localhost:29092
  schema-registry-url: localhost:8081
  schema-registry-url-key: schema.registry.url

kafka-producer-data:
  key-serializer-class: org.apache.kafka.common.serialization.StringSerializer
  value-serializer-class: io.confluent.kafka.serializers.KafkaAvroSerializer

kafka-consumer-data:
  key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer