---
# Global variables
{{- $postgresDeploymentName := .Values.postgresDeploymentName }}
{{- $serviceDeploymentName := .Values.serviceDeploymentName }}
{{- $postgresServiceName := .Values.postgresName }}
{{- $replicaCount := .Values.replicaCount }}
{{- $namespace :=  .Values.namespace }}
{{- $serviceName := .Chart.Name }}

# Account Service
{{- with .Values.accountService }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $serviceDeploymentName }}
  namespace: {{ $namespace }}
  labels:
    app: {{ $serviceDeploymentName }}
spec:
  replicas: {{ $replicaCount }}
  selector:
    matchLabels:
      app: {{ $serviceDeploymentName }}
  template:
    metadata:
      labels:
        app: {{ $serviceDeploymentName }}
    spec:
      initContainers:
        - name: init-database
          image: busybox:1.36.1
          command:
            - sh
            - -c
            - >
              until nslookup {{ printf "%s.%s.svc.cluster.local"  $postgresServiceName $namespace }}; do
                echo 'Waiting for postgres DB to initiate';
                sleep 2;
              done
      containers:
        - name: {{ $serviceName }}
          image: {{ .image }}
          env:
            {{- range .env }}
            - name: {{ .name }}
              value: {{ .value }}
            {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $serviceName }}
  namespace: {{ $namespace }}
  labels:
    app: {{ $serviceDeploymentName }}
spec:
  selector:
    app: {{ $serviceDeploymentName }}
  ports:
    - name: service-port
      protocol: TCP
      port: {{ .port }}
{{- end }}
---
# Account postgres
{{- with .Values.postgresService }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $postgresDeploymentName }}
  namespace: {{ $namespace }}
  labels:
    app: {{ $postgresDeploymentName }}
spec:
  replicas: {{ $replicaCount }}
  selector:
    matchLabels:
      app: {{ $postgresDeploymentName }}
  template:
    metadata:
      labels:
        app: {{ $postgresDeploymentName }}
    spec:
      containers:
        - name: {{ $postgresServiceName }}
          image: {{ .image }}
          env:
            {{- range .env }}
            - name: {{ .name }}
              value: {{ .value }}
            {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $postgresServiceName }}
  namespace: {{ $namespace }}
  labels:
    app: {{ $postgresDeploymentName }}
spec:
  selector:
    app: {{ $postgresDeploymentName }}
  ports:
    - name: postgres-port
      protocol: TCP
      port: {{ .port }}
{{- end }}