---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-deployment
  namespace: default
  labels:
    app: account-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account-deployment
  template:
    metadata:
      labels:
        app: account-deployment
    spec:
      containers:
        - name: account-service
          image: com.vet.appointment.system/account-service:1.0-SNAPSHOT
          imagePullPolicy: IfNotPresent
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://localhost:5432/postgres?stringtype=unspecified&currentSchema=appointment"
            - name: KAFKA_CONFIG_BOOTSTRAP_SERVERS
              value: "localhost:29092"
            - name: KAFKA_CONFIG_SCHEMA_REGISTRY_URL
              value: "http://localhost:8081"
          resources:
            limits:
              cpu: "400m"
              memory: "512Mi"
            requests:
              cpu: "200m"
              memory: "256Mi"