---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-deployment
  namespace: default
  labels:
    app: account-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account-deployment
  template:
    metadata:
      labels:
        app: account-deployment
    spec:
      containers:
        - name: account-service
          image: com.vet.appointment.system/account-service:1.0-SNAPSHOT
#          imagePullPolicy: Never
          env:
            - name: DATABASE_HOST
              value: "account-postgres-service"
            - name: EUREKA_HOST
              value: "172.19.0.1"
#              value: "jdbc:postgresql://postgres-service:5432/postgres?stringtype=unspecified&currentSchema=account"
#            - name: SPRING_DATASOURCE_URL
#              value: "jdbc:postgresql://localhost:5432/postgres?stringtype=unspecified&currentSchema=account"
#            - name: KAFKA_CONFIG_BOOTSTRAP_SERVERS
#              value: "localhost:29092"
#            - name: KAFKA_CONFIG_SCHEMA_REGISTRY_URL
#              value: "http://localhost:8081"
          resources:
            limits:
              cpu: "500m"
              memory: "1024Mi"
            requests:
              cpu: "200m"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: account-service
  namespace: default
  labels:
    app: account-deployment
spec:
  selector:
    app: account-deployment
  ports:
    - name: account-service-port
      protocol: TCP
      port: 8181
  type: LoadBalancer