apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: default
data:
  POSTGRES_USER: "user"
  POSTGRES_PASSWORD: "admin"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: microservices-config
  namespace: default
data:
  EUREKA_HOST: "http://eureka-server-service"
  KAFKA_BOOTSTRAP_HOST: "kafka-broker-service"
  KAFKA_BOOTSTRAP_PORT: "9092"
  SCHEMA_REGISTRY_HOST: "http://schema-registry-service"