---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-service-deployment
  namespace: default
  labels:
    app: account-service-deployment
spec:
  selector:
    matchLabels:
      app: account-service-deployment
  template:
    metadata:
      labels:
        app: account-service-deployment
    spec:
      containers:
        - name: account-service
          image: com.vet.appointment.system/account-service:1.0-SNAPSHOT
          env:
            - name: DATABASE_HOST
              value: "account-postgres-service"
            - name: EUREKA_HOST
              value: "http://eureka-server-service"
            - name: KAFKA_BOOTSTRAP_HOST
              value: "kafka-broker-service"
            - name: KAFKA_BOOTSTRAP_PORT
              value: "9092"
            - name: SCHEMA_REGISTRY_HOST
              value: "http://schema-registry-service"
---
apiVersion: v1
kind: Service
metadata:
  name: account-service
  namespace: default
  labels:
    app: account-service-deployment
spec:
  selector:
    app: account-service-deployment
  ports:
    - name: account-service-port
      protocol: TCP
      port: 8181
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: appointment-service-deployment
  namespace: default
  labels:
    app: appointment-service-deployment
spec:
  selector:
    matchLabels:
      app: appointment-service-deployment
  template:
    metadata:
      labels:
        app: appointment-service-deployment
    spec:
      containers:
        - name: appointment-service
          image: com.vet.appointment.system/appointment-service:1.0-SNAPSHOT
          env:
            - name: DATABASE_HOST
              value: "appointment-postgres-service"
            - name: EUREKA_HOST
              value: "http://eureka-server-service"
            - name: KAFKA_BOOTSTRAP_HOST
              value: "kafka-broker-service"
            - name: KAFKA_BOOTSTRAP_PORT
              value: "9092"
            - name: SCHEMA_REGISTRY_HOST
              value: "http://schema-registry-service"
---
apiVersion: v1
kind: Service
metadata:
  name: appointment-service
  namespace: default
  labels:
    app: appointment-service-deployment
spec:
  selector:
    app: appointment-service-deployment
  ports:
    - name: appointment-service-port
      protocol: TCP
      port: 8183
