# Default values for infrastructure.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
namespace: default

eurekaServer:
  image: com.vet.appointment.system/eureka-server:1.0-SNAPSHOT
  port: 8761

apiGateway:
  image: com.vet.appointment.system/api-gateway:1.0-SNAPSHOT
  port: 8080
  env:
    - name: EUREKA_HOST
      value: "http://eureka-server"
    - name: JWT_SECRET
      value: "eba2564000c1fa6172fb005030cd5c173dd15e8c6e5fb8d2b67093d6dc2712ce"

zookeeper:
  image: confluentinc/cp-zookeeper:latest
  port: 2181
  env:
    - name: ZOOKEEPER_CLIENT_PORT
      value: "2181"
    - name: ZOOKEEPER_TICK_TIME
      value: "2000"
    - name: ZOOKEEPER_INIT_LIMIT
      value: "5"
    - name: ZOOKEEPER_SYNC_LIMIT
      value: "2"
    - name: ZOOKEEPER_SERVER_ID
      value: "1"

kafkaBroker:
  image: confluentinc/cp-kafka:latest
  port: 9092
  env:
    - name: KAFKA_BROKER_ID
      value: "1"
    - name: KAFKA_ZOOKEEPER_CONNECT
      value: "zookeeper-service:2181"
    - name: KAFKA_ADVERTISED_LISTENERS
      value: "PLAINTEXT://kafka-broker-service:9092,PLAINTEXT_HOST://localhost:29092"
    - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
      value: "PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
    - name: KAFKA_INTER_BROKER_LISTENER_NAME
      value: "PLAINTEXT"
    - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
      value: "1"

schemaRegistry:
  image: confluentinc/cp-schema-registry:latest
  port: 8081
  env:
    - name: SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS
      value: "PLAINTEXT://kafka-broker-service:9092"
    - name: SCHEMA_REGISTRY_HOST_NAME
      value: "schema-registry-service"
    - name: SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL
      value: "zookeeper-service:2181"
    - name: SCHEMA_REGISTRY_LISTENERS
      value: "http://0.0.0.0:8081"

kafkaUi:
  image: provectuslabs/kafka-ui:latest
  port: 9000
  env:
    - name: ZK_HOST
      value: "zookeeper-service:2181"
    - name: KAFKA_CLUSTERS_0_NAME
      value: "kafka-broker-service"
    - name: KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS
      value: "kafka-broker-service:9092"
    - name: KAFKA_CLUSTERS_0_SCHEMAREGISTRY
      value: "http://schema-registry-service:8081"

debeziumConnect:
  image: com.vet.appointment.system/debezium-connect:1.0-SNAPSHOT
  port: 8083
  env:
    # General config
    - name: GROUP_ID
      value: "1"
    - name: CONFIG_STORAGE_TOPIC
      value: "connect-config"
    - name: OFFSET_STORAGE_TOPIC
      value: "connect-offsets"
    - name: STATUS_STORAGE_TOPIC
      value: "connect-status"
    - name: BOOTSTRAP_SERVERS
      value: "kafka-broker-service:9092"
    - name: LOGGING_LEVEL
      value: "DEBUG"
    # Schema registry config
    - name: CONNECT_SCHEMA_NAME_ADJUSTMENT_MODE
      value: "avro"
    - name: KEY_CONVERTER
      value: "io.confluent.connect.avro.AvroConverter"
    - name: VALUE_CONVERTER
      value: "io.confluent.connect.avro.AvroConverter"
    - name: CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL
      value: "http://schema-registry-service:8081"
    - name: CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL
      value: "http://schema-registry-service:8081"

image:
  repository: nginx
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Automatically mount a ServiceAccount's API credentials?
  automount: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

# Additional volumes on the output Deployment definition.
volumes: []
# - name: foo
#   secret:
#     secretName: mysecret
#     optional: false

# Additional volumeMounts on the output Deployment definition.
volumeMounts: []
# - name: foo
#   mountPath: "/etc/foo"
#   readOnly: true

nodeSelector: {}

tolerations: []

affinity: {}
