# Debugging file
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-broker-deployment
  namespace: default
  labels:
    app: kafka-broker-deployment
spec:
  selector:
    matchLabels:
      app: kafka-broker-deployment
  template:
    metadata:
      labels:
        app: kafka-broker-deployment
    spec:
      containers:
        - name: kafka-broker
          image: confluentinc/cp-kafka:latest
          env:
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "zookeeper-service:2181"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "PLAINTEXT://localhost:9092,PLAINTEXT_HOST://localhost:29092"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: "PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: "PLAINTEXT"
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"